linters:
  # Отключаем все линтеры, чтобы включить только нужные
  disable-all: true

  # Включаем только определенные линтеры
  enable:
    # Базовые линтеры для проверки общего качества кода
    - errcheck          # Проверка на ошибки, которые не обрабатываются
    - gosimple          # Простейшие улучшения кода
    - govet             # Стандартная проверка кода
    - ineffassign       # Проверка на неиспользуемые присваивания
    - staticcheck       # Статический анализ кода
    - typecheck         # Проверка типов
    - unused            # Проверка на неиспользуемые переменные, импорты и т.д.

    # Дополнительные линтеры для улучшенной безопасности и стиля
    - gosec             # Проверка на возможные уязвимости
    - forcetypeassert   # Проверка принудительного приведения типов
    # - contextcheck     # Временно отключен, потому что исправление требует дополнительной работы
    - noctx             # Проверка на использование контекстов
    # - unconvert        # Временно отключен, так как избыточные преобразования типов не всегда мешают
    - unparam           # Проверка на неиспользуемые параметры функций
    - prealloc          # Предупреждения по аллокациям памяти

issues:
  # Исключения для линтеров
  exclude-rules:
    - path: pkg/supervisor/supervisor_testhelpers.go  # Указываем путь к файлу, где исключается линтер
      text: "^func.*supervisor.*(waitSettle|waitSettleError).*$"  # Шаблон для поиска функций
      linters:
        - unused  # Исключаем линтер unused для этого файла
